<?php
// config/monsters.php
return [
    'easy' => [
        [
            'id' => 1,
            'name' => 'Triangle Head',
            'hp' => 3030,
            'attack' => 1000,
            'defense' => 500,
            'image_path' => '/images/monsters/TriangleHead.png',
            'difficulty' => 'easy',
        ],
        [
            'id' => 2,
            'name' => 'Fiery Slime',
            'hp' => 1234,
            'attack' => 567,
            'defense' => 910,
            'image_path' => '/images/monsters/FierySlime.png',
            'difficulty' => 'easy',
        ],
        [
            'id' => 3,
            'name' => 'Green Goblin',
            'hp' => 2460,
            'attack' => 1870,
            'defense' => 2000,
            'image_path' => '/images/monsters/GreenGoblin.png',
            'difficulty' => 'easy',
        ],
        [
            'id' => 4,
            'name' => 'Clippy',
            'hp' => 650,
            'attack' => 973,
            'defense' => 1998,
            'image_path' => '/images/monsters/Clippy.png',
            'difficulty' => 'easy',
        ],
        [
            'id' => 5,
            'name' => 'Pixel Cultist',
            'hp' => 210,
            'attack' => 100,
            'defense' => 500,
            'image_path' => '/images/monsters/PixelCultist.png',
            'difficulty' => 'easy',
        ],
        [
            'id' => 6,
            'name' => 'Happy Balloon',
            'hp' => 10,
            'attack' => 9999,
            'defense' => 10,
            'image_path' => '/images/monsters/HappyBalloon.png',
            'difficulty' => 'easy',
        ],
    ],
    'medium' => [
        [
            'id' => 7,
            'name' => 'Jujutsu Dog',
            'hp' => 3000,
            'attack' => 101,
            'defense' => 102,
            'image_path' => '/images/monsters/JujutsuDog.png',
            'difficulty' => 'medium',
        ],
        [
            'id' => 8,
            'name' => 'Triangle Genie',
            'hp' => 1111,
            'attack' => 2222,
            'defense' => 3333,
            'image_path' => '/images/monsters/TriangleGenie.png',
            'difficulty' => 'medium',
        ],
        [
            'id' => 9,
            'name' => 'Herbivorous Hammer',
            'hp' => 1987,
            'attack' => 2000,
            'defense' => 2025,
            'image_path' => '/images/monsters/HerbivorousHammer.png',
            'difficulty' => 'medium',
        ],
        [
            'id' => 10,
            'name' => 'Car Big Arms',
            'hp' => 6000,
            'attack' => 7000,
            'defense' => 100,
            'image_path' => '/images/monsters/CarBigArms.png',
            'difficulty' => 'medium',
        ],
        [
            'id' => 11,
            'name' => 'Chef Capybara',
            'hp' => 5555,
            'attack' => 10,
            'defense' => 5555,
            'image_path' => '/images/monsters/ChefCapybara.png',
            'difficulty' => 'medium',
        ],
        [
            'id' => 12,
            'name' => 'Penguin Knife',
            'hp' => 70,
            'attack' => 3777,
            'defense' => 7,
            'image_path' => '/images/monsters/PenguinKnife.png',
            'difficulty' => 'medium',
        ],
        [
            'id' => 13,
            'name' => 'Not A Mimic',
            'hp' => 99,
            'attack' => 4999,
            'defense' => 99,
            'image_path' => '/images/monsters/NotAMimic.png',
            'difficulty' => 'medium',
        ],
    ],
    'hard' => [
        [
            'id' => 14,
            'name' => 'Job The Reality Checker',
            'hp' => 10,
            'attack' => 9999,
            'defense' => 9999,
            'image_path' => '/images/monsters/JobTheRealityChecker.png',
            'difficulty' => 'hard',
        ],
        [
            'id' => 15,
            'name' => 'Yggdrasils Cousin',
            'hp' => 1337,
            'attack' => 50,
            'defense' => 7331,
            'image_path' => '/images/monsters/YggdrasilsCousin.png',
            'difficulty' => 'hard',
        ],
        [
            'id' => 16,
            'name' => 'Billy The Aquatic Vertebrate',
            'hp' => 5432,
            'attack' => 876,
            'defense' => 9,
            'image_path' => '/images/monsters/BillyTheAquaticVertebrate.png',
            'difficulty' => 'hard',
        ],
        [
            'id' => 17,
            'name' => 'Caloric No Deficit',
            'hp' => 250,
            'attack' => 5000,
            'defense' => 50,
            'image_path' => '/images/monsters/CaloricNoDeficit.png',
            'difficulty' => 'hard',
        ],
        [
            'id' => 18,
            'name' => 'Insomnia Inducer',
            'hp' => 1000,
            'attack' => 1206,
            'defense' => 499,
            'image_path' => '/images/monsters/InsomniaInducer.png',
            'difficulty' => 'hard',
        ],
        [
            'id' => 19,
            'name' => 'Viru Sahastrabudhhe',
            'hp' => 404,
            'attack' => 404,
            'defense' => 4040,
            'image_path' => '/images/monsters/ViruSahastrabudhhe.png',
            'difficulty' => 'hard',
        ],
    ]
];
